services:
  crossposter:
    build: .
    image: ghcr.io/linus2punkt0/bluesky-crossposter:latest
    restart: always
    environment:
      BSKY_HANDLE:
      BSKY_PASSWORD:
      MASTODON_HANDLE:
      MASTODON_INSTANCE:
      MASTODON_TOKEN:
      TWITTER_APP_KEY:
      TWITTER_APP_SECRET:
      TWITTER_ACCESS_TOKEN:
      TWITTER_ACCESS_TOKEN_SECRET:
      # See defaults in settings.py
      INPUT_SOURCE:
      TWITTER_CROSSPOSTING: ${TWITTER_CROSSPOSTING:-true}
      MASTODON_CROSSPOSTING: ${MASTODON_CROSSPOSTING:-true}
      BLUESKY_CROSSPOSTING: ${MASTODON_CROSSPOSTING:-false}
      MASTODON_MENTIONS:
      MENTIONS:
      POST_DEFAULT:
      LANG_TOGGLE:
      QUOTE_POSTS:
      RETWEETS:
      MAX_RETRIES:
      POST_TIME_LIMIT:
      MAX_PER_HOUR:
      OVERFLOW_POST:
      CROSS_DELETE:
      RATE_LIMIT_BUFFER:
      LOG_LEVEL:
      MASTODON_VISIBILITY:
      ALLOW_REPLY:
      PRIVACY:
      # job interval, defaults to 1 hour(the max lag between bluesky and twitter/mastodon)
      RUN_INTERVAL: ${RUN_INTERVAL:-3600}
    volumes:
      - ./dbhost:/db
      - ./backup:/backup
